default_context:
  _pegasus_version: 2022.11.1
  author_name: Frank
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: Software meant to save you time editing documents and allow you to
    spend more time bringing in customers
  domain_name: localhost:8000
  email: frankabbondanza@gmail.com
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  project_name: QuicDoc
  project_slug: quicdoc
  stripe_payment_mode: checkout
  subscription_billing_model: default
  use_2fa: y
  use_api_keys: y
  use_docker: y
  use_impersonation: y
  use_sentry: y
  use_subscriptions: y
  use_teams: y
  use_translations: y
  use_wagtail: n
